#!/usr/bin/env python3
"""
Compare app OCR output vs official rknn_lprnet_demo on the same dumped OCR inputs.

Input index CSV is generated by fpga_lpr_display when using:
  --ocr-crop-dump-dir <dir>
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import subprocess
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def norm_text(s: str) -> str:
    if s is None:
        return ""
    out = []
    for ch in s.strip():
        if ch in {" ", "\t", "-", "_"}:
            continue
        if "a" <= ch <= "z":
            out.append(chr(ord(ch) - 32))
        else:
            out.append(ch)
    return "".join(out)


def extract_demo_text(stdout: str, stderr: str) -> str:
    data = (stdout or "") + "\n" + (stderr or "")
    lines = [x.strip() for x in data.splitlines() if x.strip()]
    stop_tokens = {
        "FMT", "NHWC", "NCHW", "MODEL", "INPUT", "OUTPUT", "RKNN_RUN",
        "TENSORS", "SIZE", "IMAGE", "RESULT",
    }

    # Typical:
    #   "车牌识别结果: 湘F6CL03"
    #   "识别结果: 湘F6CL03"
    #   "result: XF6CL03"
    for ln in reversed(lines):
        m = re.search(
            r"(?:车牌识别结果|识别结果|杞︾墝璇嗗埆缁撴灉|璇嗗埆缁撴灉|result)\s*[:：锛歖]\s*(\S+)$",
            ln,
            flags=re.IGNORECASE,
        )
        if m:
            return norm_text(m.group(1))

    # Fallback: choose last plausible OCR token, not path/key-value/log.
    for ln in reversed(lines):
        low = ln.lower()
        if ("input tensors" in low or "output tensors" in low or "model input" in low or
                "model is " in low or "origin size" in low or "input image" in low):
            continue
        if "=" in ln or "/" in ln or "\\" in ln:
            continue
        if ":" in ln and not re.search(
            r"(?:result|识别结果|车牌识别结果|璇嗗埆缁撴灉|杞︾墝璇嗗埆缁撴灉)\s*[:：锛歖]",
            ln,
            flags=re.IGNORECASE,
        ):
            continue
        toks = ln.split()
        if not toks:
            continue
        cand = norm_text(toks[-1])
        if cand in stop_tokens:
            continue
        if re.match(r"^[\u4e00-\u9fffA-Z0-9]{1,12}$", cand):
            return cand
    return ""

def run_demo(demo_bin: str, model: str, image_path: str, timeout_s: float) -> Tuple[str, str]:
    p = subprocess.run(
        [demo_bin, model, image_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="ignore",
        timeout=timeout_s,
        check=False,
    )
    return p.stdout, p.stderr


def metric_pack(texts: List[str], gt: str, blanks: Optional[List[Optional[float]]] = None) -> Dict[str, object]:
    n = len(texts)
    den = n if n > 0 else 1
    nonempty = sum(1 for t in texts if t)
    len7 = sum(1 for t in texts if len(t) >= 7)
    exact = sum(1 for t in texts if gt and t == gt)
    blank_valid = [b for b in (blanks or []) if b is not None]
    return {
        "count": n,
        "ocr_nonempty_ratio": nonempty / den,
        "len_ge_7_ratio": len7 / den,
        "exact_match_ratio": (exact / den) if gt else None,
        "blank_top1_mean": (sum(blank_valid) / len(blank_valid)) if blank_valid else None,
        "top_texts": Counter([t for t in texts if t]).most_common(10),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="Compare app OCR vs official demo on same OCR input crops.")
    ap.add_argument("--index", required=True, help="index.csv generated in --ocr-crop-dump-dir")
    ap.add_argument("--demo-bin", required=True, help="path to rknn_lprnet_demo binary")
    ap.add_argument("--model", required=True, help="path to OCR rknn model")
    ap.add_argument("--max-samples", type=int, default=20, help="max samples to evaluate")
    ap.add_argument("--gt-text", default="", help="ground-truth plate text")
    ap.add_argument("--timeout", type=float, default=3.0, help="per-image demo timeout seconds")
    ap.add_argument("--out-csv", default="", help="optional per-sample output csv")
    ap.add_argument("--out-json", default="", help="optional summary output json")
    args = ap.parse_args()

    gt = norm_text(args.gt_text) if args.gt_text else ""
    rows: List[Dict[str, str]] = []

    with Path(args.index).open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        needed = {"sample_id", "frame_id", "app_text", "ocr_input_path"}
        got = set(r.fieldnames or [])
        if not needed.issubset(got):
            raise ValueError(f"index missing columns: need={sorted(needed)} got={sorted(got)}")
        for i, row in enumerate(r):
            if i >= args.max_samples:
                break
            rows.append(row)

    app_texts: List[str] = []
    demo_texts: List[str] = []
    app_blank_top1: List[Optional[float]] = []
    sample_rows: List[Dict[str, str]] = []

    for row in rows:
        img = row["ocr_input_path"]
        app_t = norm_text(row.get("app_text", ""))
        app_blank_raw = (row.get("app_blank_top1", "") or "").strip()
        try:
            app_blank = float(app_blank_raw) if app_blank_raw != "" else None
        except ValueError:
            app_blank = None
        stdout, stderr = run_demo(args.demo_bin, args.model, img, args.timeout)
        demo_t = extract_demo_text(stdout, stderr)

        app_texts.append(app_t)
        demo_texts.append(demo_t)
        app_blank_top1.append(app_blank)
        sample_rows.append(
            {
                "sample_id": row.get("sample_id", ""),
                "frame_id": row.get("frame_id", ""),
                "image": img,
                "app_text": app_t,
                "demo_text": demo_t,
                "app_blank_top1": "" if app_blank is None else f"{app_blank:.4f}",
                "same_text": "1" if app_t == demo_t else "0",
            }
        )

    summary = {
        "gt_text": gt if gt else None,
        "samples": len(sample_rows),
        "app": metric_pack(app_texts, gt, app_blank_top1),
        "demo": metric_pack(demo_texts, gt),
        "app_demo_same_ratio": (
            sum(1 for i in range(len(sample_rows)) if app_texts[i] == demo_texts[i]) / len(sample_rows)
            if sample_rows
            else 0.0
        ),
    }

    print(json.dumps(summary, ensure_ascii=False, indent=2))

    if args.out_csv:
        out_csv = Path(args.out_csv)
        out_csv.parent.mkdir(parents=True, exist_ok=True)
        with out_csv.open("w", encoding="utf-8", newline="") as f:
            w = csv.DictWriter(
                f,
                fieldnames=["sample_id", "frame_id", "image", "app_text", "demo_text", "app_blank_top1", "same_text"],
            )
            w.writeheader()
            w.writerows(sample_rows)

    if args.out_json:
        out_json = Path(args.out_json)
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())


